##### Instructions
- Keep the original structure, you may add additional code cells and/or mark-down cells for clarity, legibility and/or structure.
- Add the required descriptions, explanations, justifications to the mark-down cells. You can find more mark-down tips & tricks online, for example [here](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html) and [here](https://www.ibm.com/docs/en/watson-studio-local/1.2.3?topic=notebooks-markdown-jupyter-cheatsheet)

# EXAM03: Data Science Group Assignment - Iteration 1

**Group name:** Databazen😎

**Student names & numbers:**
* [Xander UijtdeHaag] - [Student no.100546]
* [Jamie Eversdijk] - [Student no.000101617]
* [Jero den Exter] - [Student no.000100883]

---

## 0. Iteration setup

**Import libraries**

In [3]:
%pip install pandas
%pip install matplotlib
%pip install scikit-learn

import pandas as pd
import matplotlib.pyplot as plt

Requirement already satisfied: pandas in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (2.4.2)
Requirement already satisfied: packaging>=20.0 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: scikit-learn in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**Load dataset(s)**

In [4]:
df = pd.read_csv('Data/Sus scrofa.csv')

C:\Users\User\AppData\Local\Temp\ipykernel_17252\1270535641.py:1: DtypeWarning: Columns (0: Sus scrofa) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Data/Sus scrofa.csv')

---

## 1. Business Understanding
*Rubric: LO 6.4D (Reflection on Process)**

**Business objective(s)**

Wij willen inzicht krijgen in de leefgebieden in Nederland van wilde zwijnen van op zijn minst 20 verschillende plaatsen zodat wij weten waar de zwijnen leven tussen 2010 en 2025.


**Acceptence criteria(s)**
Duidelijk inzicht voor waar de meeste wilde zwijnen leven in Nederland

Minstens 20 verschillende plaatsen halen uit de data.

Alleen data tussen 2010 en 2025 gebruiken

Gebieden met hoge en lage hoeveelheden van zwijnen zijn te scheiden.


**Data mining goal(s)**
Met behulp van een classificatie model inzicht krijgen waar de meeste wilde zwijnen van Nederland leven tussen 2010 en 2025.


**Success criteria**
Het model heeft een accuracy van 80% op het vinden van wilde zwijnen.

Het model heeft een recall van 75% en een precision van op zijn minst 70%


*Determine success criteria for this iteration (the benchmark)*
Wij zijn voor deze percentages gegaan omdat wij denken dat dit het hoogst is dat wij  kunnen halen met hoe groot de dataset is. Verder denken wij dat de 80% drempel logisch is omdat het betrouwbaar genoeg zou zijn voor het voorspellen van zwijnen.

Een recall(Hoeveel echte positieve zijn er?) van 75% Wij vinden liever de gebieden waar de zwijnen leven als dat wij ze missen. Daarom hebben wij gekozen voor 75%. Deze grens is nodig voor het zien van de belangrijke gebieden waar de zwijnen leven. Het is realistisch te behalen in onze ogen.

precision (Hoe vaak een positieve voorspelling echt klopt) Deze is 70% omdat het belangrijk is dat wij alleen gebieden zien waar ook echt zwijnen zijn. Deze is iets lager als de rest omdat dit eigenlijk de minste prioriteit heeft.

**Exploratory data analysis**

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12558786 entries, 0 to 12558785
Data columns (total 6 columns):
 #   Column                     Dtype
---  ------                     -----
 0   decimalLatitude            float64
 1   decimalLongitude           float64
 2   eventDate                  str
 3   total_observations         float64
 4   speciesgroup_observations  int64
 5   Sus scrofa                 object
dtypes: float64(3), int64(1), object(1), str(1)
memory usage: 574.9+ MB

In [30]:
df.head()

,decimalLatitude,decimalLongitude,eventDate,total_observations,speciesgroup_observations,Sus scrofa
0,50.75,5.65,2010-01-01,0.0,0,0
1,50.75,5.65,2010-01-02,26.0,0,0
2,50.75,5.65,2010-01-03,3.0,0,0
3,50.75,5.65,2010-01-04,0.0,0,0
4,50.75,5.65,2010-01-05,0.0,0,0

In [32]:
df.describe()

,decimalLatitude,decimalLongitude,total_observations,speciesgroup_observations
count,1.255879e+07,1.255879e+07,1.255878e+07,1.255879e+07
mean,5.222995e+01,5.532896e+00,8.125083e+00,2.262421e-01
std,6.647267e-01,8.779710e-01,4.830242e+01,2.521836e+00
min,3.500000e+00,3.350000e+00,0.000000e+00,0.000000e+00
25%,5.170000e+01,4.900000e+00,0.000000e+00,0.000000e+00
50%,5.220000e+01,5.650000e+00,1.000000e+00,0.000000e+00
75%,5.280000e+01,6.200000e+00,6.000000e+00,0.000000e+00
max,5.350000e+01,5.340000e+01,1.000400e+05,1.637000e+03

In [33]:
df.isna().sum()

decimalLatitude              0
decimalLongitude             0
eventDate                    0
total_observations           2
speciesgroup_observations    0
Sus scrofa                   0
dtype: int64

---

## 2. Data Understanding
*Rubric: LO 7.3Q (Visuals) & LO 6.4C (Process)*

**Data exploration**

*Include summary statistics and descriptions of data types below. Describe your findings.*

De datatypes zijn int int float object en object. Wij hebben gekozen om de Galactic credits te gebruiken als een soort target. Dit is volgens ons de enige kolom die echt helpt bij het vinden van de juiste prijs van de schepen. De shipId is niet echt logisch om te gebruiken omdat het unieke waardes zijn van de schepen. De model cycle is ook niet logisch omdat het bouwjaar niet heel veel betekend voor ons doel. De andere kolommen zijn geen nummers en dus ook niet logisch

In [3]:
df.dtypes

decimalLatitude              float64
decimalLongitude             float64
eventDate                     object
total_observations           float64
speciesgroup_observations      int64
Sus scrofa                    object
dtype: object

In [5]:
# OPTIONAL CODE CELL: Additional preprocessing steps

In [5]:
print("First few rows of the dataset:")
print(df.head())
print("\nDataset info:")
print(df.info())
print("\nSummary statistics:")
print(df.describe())

First few rows of the dataset:
   decimalLatitude  decimalLongitude   eventDate  total_observations  \
0            50.75              5.65  2010-01-01                 0.0
1            50.75              5.65  2010-01-02                26.0
2            50.75              5.65  2010-01-03                 3.0
3            50.75              5.65  2010-01-04                 0.0
4            50.75              5.65  2010-01-05                 0.0

   speciesgroup_observations Sus scrofa
0                          0          0
1                          0          0
2                          0          0
3                          0          0
4                          0          0

Dataset info:
<class 'pandas.DataFrame'>
RangeIndex: 12558786 entries, 0 to 12558785
Data columns (total 6 columns):
 #   Column                     Dtype
---  ------                     -----
 0   decimalLatitude            float64
 1   decimalLongitude           float64
 2   eventDate                  str
 3   total_observations         float64
 4   speciesgroup_observations  int64
 5   Sus scrofa                 object
dtypes: float64(3), int64(1), object(1), str(1)
memory usage: 574.9+ MB
None

Summary statistics:
       decimalLatitude  decimalLongitude  total_observations  \
count     1.255879e+07      1.255879e+07        1.255878e+07
mean      5.222995e+01      5.532896e+00        8.125083e+00
std       6.647267e-01      8.779710e-01        4.830242e+01
min       3.500000e+00      3.350000e+00        0.000000e+00
25%       5.170000e+01      4.900000e+00        0.000000e+00
50%       5.220000e+01      5.650000e+00        1.000000e+00
75%       5.280000e+01      6.200000e+00        6.000000e+00
max       5.350000e+01      5.340000e+01        1.000400e+05

       speciesgroup_observations
count               1.255879e+07
mean                2.262421e-01
std                 2.521836e+00
min                 0.000000e+00
25%                 0.000000e+00
50%                 0.000000e+00
75%                 0.000000e+00
max                 1.637000e+03

---

## 4. Modeling
*Rubric: LO 6.4C (Data Science Steps)*

**Model setup**
*Describe and justify the creation of your simple benchmark model to predict Galactic_Credits*

In [9]:
# CODE CELL: Model training and setup code
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import root_mean_squared_error

# Target is galacric credits
target = df_final['Galactic_Credits']
# Splitsen data in een train en test set
target_train, target_test = train_test_split(target, test_size=0.2, random_state=42)

# Voorspelling model
value = target_train.median()

pred_train = [value] * len(target_train)

pred_test = [value] * len(target_test)

Train_test_split is de methode die wij hebben geleerd om een dataset op te delen, zodat we een kolom kunnen gebruiken om toekomstige waardes te voorspellen.

Hierin wordt de voorspelling gemaakt met train_test_split wat wordt opgedeeld in 80% train en 20% split wat de test_size=0.2 aangeeft. De random state is 42 wat aangeeft dat het altijd hetzelfde wordt verdeeld en je het vaker opnieuw kan gebruiken. Tot slot maak je de voorspelling van de train d.m.v. het gemiddelde te pakken van de target en dat * target_train en -test te doen.

**Testing and performance**
*Describe how you tested the model and interpret the metrics. Make sure to present the metrics in a clear overview.*

In [12]:
# CODE CELL: Model evaluation code
# MAE en RMSE van train en test
print('MAE of train set:', mean_absolute_error(target_train, pred_train))
print('MAE of test set:', mean_absolute_error(target_test, pred_test))
print('RMSE of train set:', root_mean_squared_error(target_train, pred_train))
print('RMSE of test set:', root_mean_squared_error(target_test, pred_test))

MAE of train set: 11079.722925715712
MAE of test set: 11058.98746912381
RMSE of train set: 14663.368917696056
RMSE of test set: 14594.354455063114

MAE en RMSE van de train is de daadwerkelijke waardes van Galactic_Credits en de test is de voorspelling ervan. De MAE van de trainingsset is ongeveer 11.079 en van de testset ongeveer 11.058. Het verschil van 11 Galactic_Credits is zeer klein, wat aangeeft dat het model niet ver afwijkt. Het verschil in RMSE tussen train en test is ongeveer 69. Dit is ook helemaal niet veel vergeleken hoe groot de dataset is.

MAE en RMSE laat de fouten binnen een data set zien en dus weet je waar het mis gaat als dit verschil groot is tussen voorspelling en werkelijkheid. MAE laat zien hoeveel de voorspelling er gemiddeld naast zit wat de algemene nauwkeurigheid van de dataset, RMSE laat de grote fouten zien binnen een dataset dus de outliers door ze te kwadrateren waardoor je deze kan onderzoeken of ze daadwerkelijk kloppen of niet en dan in een wortel zodat het niet een overdreven groot getal is.

---

## 5. Evaluation
*Rubric: LO 6.4C (Results vs. Objectives)*

**Assessment against succes criteria** 
*What is the difference between the metrics? What does this mean? Did you meet the goals set in the Business Understanding?*
Wij hebben de mean absolute error en de mean squared error gebruikt om te kijken hoeveel de voorspelde en echte waardes afwijken van elkaar. De mean absolute error heeft het verschil tussen de train 11.598 en 11.639 dit is een klein verschil en is dus goed. Wij wijken weinig af van de echte waardes. De mse heeft een iets groter verschil van ongeveer 15 miljoen. Dit komt waarschijnlijk door een aantal uitschieters die de waarde zo hoog maken. Wij denken dat onze methode goed genoeg is, maar wel beter kan.


**Key findings and limitations**
*What did you learn? What are the limitations of this current model?*
Wij hebben geleerd dat ons model een aantal goede delen heeft. Het is een klein verschil bij het mae. Dit is goed, want het model wijkt niet ver af van de werkelijkheid. Het levert goede resultaten op. Het levert meer betrouwbaarheid op dan het onderbuikgevoel wat hiervoor is gebruikt. De nadelen zijn dat er nog steeds uitschieters in zitten die de waardes aanpassen. Het gebruikt ook alleen de galactic credits kolom wat wel kan omdat het de target is, maar het kan wel beter.

---

## 6 Personal Contribution
*Rubric: LO 7.3P (Equal Contribution)*

| Student name | Contribution | Personal lessons learned |
| :--- | :--- | :--- |
| Xander UijtdeHaag | Business understanding, Data preperation, Evaluation | Ik heb veel geleerd over het belang en het nut van Data-driven worden en het doel van data-driven worden als bedrijf. Ook heb ik technisch veel geleerd bij Data preperation en dit lukte na wat dingen uitzoeken best makkelijk. Ook heb ik veel geleerd over hoe de opdracht eruit ziet en hoe data science een beetje in elkaar zit |
| Jamie Eversdijk | Geheel modeling, Evaluation van findings mae en rmse | Ik heb geleerd hoe je met een baseline model en een train-test split een eerlijk nulpunt bepaalt voor de voorspellingen. Door het gemiddelde te gebruiken en dit te testen met MAE en MSE, maken deze metrics het mogelijk om voorspellingen met feitelijke informatie te beoordelen. |
| Jero den Exter | Data understanding alles gemaakt, Data preperation poging tot het maken van een logische code van gecleande data, maar miste wel wat delen. Evaluation | Veel geleerd over het werken met een grote dataset. Het data preperation gedeelte vond ik wel lastig. Geleerd over data understanding en alle handige python commands daarbij. Verder ook geleerd hoe je een histogram kan maken met python. Het deleete van Data preperation vond ik wel het moeilijkst. Ik vond de spelfouten nog al lastig uit de dataset te halen. Dit heeft iemand anders ook uiteindelijk over gepakt. |